### ISSUE TITLE
GeneratePHPDoc seems broken since last Update

### ISSUE THREAD

**Issue by m-lotze-7o7** [phpfmt/sublime-phpfmt#203]
After the last update GeneratePHPDoc seems broken.

Sublime 3, phpfmt package user settings:

```
{
	"enable_auto_align": true,
	"format_on_save": true,
	"ignore_list":
	[
		".blade.php"
	],
	"indent_with_space": true,
	"laravel_deprecated_warning": true,
	"laravel_style": false,
	"passes":
	[
		"AlignDoubleArrow",
		"AlignDoubleSlashComments",
		"AlignEquals",
		"AlignGroupDoubleArrow",
		"AlignTypehint",
		"AlmanStyleBraces",
		"AutoPreincrement",
		"DoubleToSingleQuote",
		"GeneratePHPDoc",
		"IndentTernaryConditions",
		"MergeElseIf",
		"PrettyPrintDocBlocks",
		"SpaceBetweenMethods",
		"StripExtraCommaInArray",
		"StripNewlineAfterClassOpen",
		"StripNewlineAfterCurlyOpen",
		"TightConcat",
		"ShortArray",
		"ReindentSwitchBlocks"
	],
	"php55warning": true,
	"php_bin": "c:/xampp/php56/php.exe",
	"psr1": false,
	"psr2": true,
	"smart_linebreak_after_curly": true,
	"version": 4,
	"visibility_order": true,
	"yoda": true
}
```

on saving a .php file a docblock like this

```
/**
 * Create a new command instance.
 *
 * @return void
 */
public function __construct()
{
```
becomes this
```
/**
 * Create a new command instance.
 *
 * @return void
 */
/**
 * @var mixed
 */
public function __construct()
{
```
when saving again, it becomes this
```
/**
 * Create a new command instance.
 *
 * @return void
 */
/**
 * @var mixed
 */
/**
 * @var mixed
 */
public function __construct()
{
```
so the docblock is added everytime.

**Comment by ccirello** [comment]
@m-lotze-7o7 I am sorry for this bug. I will contact the person that made the change last time on this pass.

**Comment by Shaked** [comment]
Hey @m-lotze-7o7 

I am sorry for this bug. 

Can you please provide the following information: 

- The result of `phpfmt: troubleshoot information`
- The information you have in your console after adding `"debug":1` to your Sublime settings

Thanks!

**Comment by ccirello** [comment]
@m-lotze-7o7 I recommend you provide a gist with more code context. It could be the case a previous doc block or piece of code is derailing this pass.

**Comment by m-lotze-7o7** [comment]
@Shaked:

here is the information in my console after saving a file with GeneratePHPDoc on:

```
phpfmt (php_ver) cmd:
 ['c:/xampp/php56/php.exe', '-v']
phpfmt (php_ver) out:
 PHP 5.6.10 (cli) (built: Jun 10 2015 15:59:59) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

phpfmt (php_ver) err:
 

Exception in thread Thread-3815:
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "phpcs in C:\Users\Lotze\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 476, in run
  File "phpcs in C:\Users\Lotze\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 143, in get_errors
  File "phpcs in C:\Users\Lotze\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 219, in execute
  File "phpcs in C:\Users\Lotze\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 222, in parse_report
  File "phpcs in C:\Users\Lotze\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 173, in shell_out
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

Found styles linked in HTML
[]
```

**Comment by m-lotze-7o7** [comment]
@ccirello:

You are right. It seems not every doc block is affected. in the code below only the doc block for the function fire is affected:

```
<?php

use Illuminate\Console\Command;

class exportItems extends Command
{
    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'export:items';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = '....';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    /**
     * @var mixed
     */
    /**
     * @var mixed
     */
    /**
     * @var mixed
     */
    public function fire()
    {
        .....
    }

    /**
     * Get the console command arguments.
     *
     * @return array
     */
    protected function getArguments()
    {
        .....
    }

    /**
     * Get the console command options.
     *
     * @return array
     */
    protected function getOptions()
    {
        .....
    }

}
```

**Comment by Shaked** [comment]
Hey @m-lotze-7o7 

The issue has been fixed in the [PR 73](https://github.com/phpfmt/php.tools/pull/73) and released. 

You can update the plugin and it should work fine. 

Thank you!

**Comment by m-lotze-7o7** [comment]
Great. Works. Thank you
