### ISSUE TITLE
phpcs not found - Mac El Captian

### ISSUE THREAD

**Issue by clubdesign** [phpfmt/sublime-phpfmt#239]
Hey Guys,

i can't get it running on Mac OSX El Capitan 10.11.3. I have added PHP 5.6 as custom version to the normal mac install. 

php -v gives me PHP 5.6.17 (cli) (built: Jan  8 2016 10:51:07).
phpcs --version gives me PHP_CodeSniffer version 2.5.1 (stable)

When i run format command, either on save or triggered i get the following error in the console:

```
('phpfmt (oracle file): not found',)
('phpfmt (php_ver) cmd:\n', ['/usr/local/php5/bin/php', '-v'])
('phpfmt (php_ver) out:\n', 'PHP 5.6.17 (cli) (built: Jan  8 2016 10:51:07) \nCopyright (c) 1997-2015 The PHP Group\nZend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies\n    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies\n    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans\n')
('phpfmt (php_ver) err:\n', '')
('phpfmt (php version):\nPHP 5.6.17 (cli) (built: Jan  8 2016 10:51:07) \nCopyright (c) 1997-2015 The PHP Group\nZend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies\n    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies\n    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans\n\nphpfmt (php tokenizer) found\n\nphpfmt (fmt.phar version):\n/Users/user/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar 19.3.0\n\nPHP 5.5 compatibility mode: False\n\n',)
('cmd_fmt: ', ['/usr/local/php5/bin/php', '/Users/user/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar', '--config=/Users/user/Library/Application Support/Sublime Text 3/Packages/phpfmt/php.tools.ini', '--psr2', '--indent_with_space=4', '--smart_linebreak_after_curly', '--passes=ReindentSwitchBlocks', '-v', '-o=-', '-'])
('p:\n', 0)
('err:\n', 'Used passes: EliminateDuplicatedEmptyLines, RTrim, PSR2IndentWithSpace, LeftAlignComment, PSR2SingleEmptyLineAndStripClosingTag, PSR2ModifierVisibilityStaticOrder, PSR2CurlyOpenNextLine, PSR2LnAfterNamespace, PSR2KeywordsLowerCase, ReindentEqual, Reindent, ReindentObjOps, ReindentSwitchBlocks, ReindentColonBlocks, SplitCurlyCloseAndTokens, ResizeSpaces, StripExtraCommaInList, MergeDoubleArrowAndArray, MergeCurlyCloseAndDoWhile, MergeParenCloseWithCurlyOpen, NormalizeLnAndLtrimLines, ExtraCommaInArray, SmartLnAfterCurlyOpen, AddMissingCurlyBraces, OrderAndRemoveUseClauses, NormalizeIsNotEquals, RemoveIncludeParentheses, TwoCommandsInSameLine\n')
('',)
Exception in thread Thread-87:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "phpcs in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 476, in run
  File "phpcs in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 143, in get_errors
  File "phpcs in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 219, in execute
  File "phpcs in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 222, in parse_report
  File "phpcs in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 173, in shell_out
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'phpcs'
```

So i guess somehow Code Sniffer is missing, but i don't know what i can change?

Thanks

**Comment by ccirello** [comment]
@clubdesign PHP_CodeSniffer is not part of phpfmt. You should file a complain to `Phpcs.sublime-package` package owner.

**Comment by ccirello** [comment]
You can see by these lines that phpfmt worked just fine. 
```
('phpfmt (oracle file): not found',)
('phpfmt (php_ver) cmd:\n', ['/usr/local/php5/bin/php', '-v'])
('phpfmt (php_ver) out:\n', 'PHP 5.6.17 (cli) (built: Jan  8 2016 10:51:07) \nCopyright (c) 1997-2015 The PHP Group\nZend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies\n    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies\n    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans\n')
('phpfmt (php_ver) err:\n', '')
('phpfmt (php version):\nPHP 5.6.17 (cli) (built: Jan  8 2016 10:51:07) \nCopyright (c) 1997-2015 The PHP Group\nZend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies\n    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies\n    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans\n\nphpfmt (php tokenizer) found\n\nphpfmt (fmt.phar version):\n/Users/user/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar 19.3.0\n\nPHP 5.5 compatibility mode: False\n\n',)
('cmd_fmt: ', ['/usr/local/php5/bin/php', '/Users/user/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar', '--config=/Users/user/Library/Application Support/Sublime Text 3/Packages/phpfmt/php.tools.ini', '--psr2', '--indent_with_space=4', '--smart_linebreak_after_curly', '--passes=ReindentSwitchBlocks', '-v', '-o=-', '-'])
('p:\n', 0)
('err:\n', 'Used passes: EliminateDuplicatedEmptyLines, RTrim, PSR2IndentWithSpace, LeftAlignComment, PSR2SingleEmptyLineAndStripClosingTag, PSR2ModifierVisibilityStaticOrder, PSR2CurlyOpenNextLine, PSR2LnAfterNamespace, PSR2KeywordsLowerCase, ReindentEqual, Reindent, ReindentObjOps, ReindentSwitchBlocks, ReindentColonBlocks, SplitCurlyCloseAndTokens, ResizeSpaces, StripExtraCommaInList, MergeDoubleArrowAndArray, MergeCurlyCloseAndDoWhile, MergeParenCloseWithCurlyOpen, NormalizeLnAndLtrimLines, ExtraCommaInArray, SmartLnAfterCurlyOpen, AddMissingCurlyBraces, OrderAndRemoveUseClauses, NormalizeIsNotEquals, RemoveIncludeParentheses, TwoCommandsInSameLine\n')
('',)
```

**Comment by clubdesign** [comment]
Oh. So the problem isn't within phpfmt.. Dang, did not see that. SORRY!
