### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe with ST Build 3103

### ISSUE THREAD

**Issue by kachar** [phpfmt/sublime-phpfmt#246]
After I've upgraded to Build 3103 phpfmt is throwing the following error.

Reinstallation of the package does not resolve the problem.

Using php-5.6.18

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "C:\Users\user1144\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 776, in run
    src = dofmt(self, self.view, None, src, True)
  File "C:\Users\user1144\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 243, in dofmt
    p.stdin.write(src.encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
```

Maybe related to #164

**Comment by ccirello** [comment]
It is a problem that happens on window machines every once in a while. It has to do with permissions, the php binary being able to actually find the phar file. 

Also be careful how you start ST3. IIRC, there are two binaries or one binary and one shortcut. If you start St 3 using the wrong one, this error also happens.
